import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const versionPath = resolve(root, "VERSION");
const outPath = resolve(root, "src", "version.ts");

const version = readFileSync(versionPath, "utf8").trim() || "0.0.0";
const buildTime = new Date().toISOString();

let commitHash = "unknown";
try {
  commitHash = execSync("git rev-parse HEAD", { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
    .toString()
    .trim();
} catch {
  commitHash = "unknown";
}

const content = `// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "${version}";
export const BUILD_TIME = "${buildTime}";
export const COMMIT_HASH = "${commitHash}";
`;

writeFileSync(outPath, content, "utf8");
console.log(`Wrote ${outPath}`);
