// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "3.1";
export const BUILD_TIME = "2026-01-21T15:28:17.491Z";
export const COMMIT_HASH = "8b6c09385b495897f398363549e7e27fb6ebfdd1";
